### ISSUE TITLE
IPv6 resolved over IPv4 as server address

### ISSUE THREAD

**Issue by metalglove** [RaidMax/IW4MAdmin-Master#15]
The RaidMax-Admin server resolves my server as IPv6 instead of IPv4.

From https://master.iw4.zip/instance/
```
{
    "servers": [
        {
            "ip": "2a00:bba0:1212:700:29f4:1053:f803:608b",
            "clientnum": 0,
            "gametype": "dom",
            "id": 12700127016,
            "maxclientnum": 18,
            "port": 27016,
            "map": "mp_invasion",
            "version": "H1 MP 1.15 build 1251288 Tue Jul 23 13:38:30 2019 win64",
            "game": "H2M",
            "hostname": "^3[EU] ^2GLOVALI'S FAVORITE MAPS MWR/MW2 ON DOM"
        }
    ],
    "uptime": 2766,
    "id": "33a6905e-09d8-4809-a05c-a8db7cbc8553",
    "last_heartbeat": 1724329911,
    "ip_address": "2a00:bba0f4:f803b",
    "webfront_url": "http://2a00:bba0:1212:700:29f4:1053:f803:608b:1624",
    "version": "2024.8.16.1"
},
```

I assume that is because the remote address of the request is used as server IP.

https://github.com/RaidMax/IW4MAdmin-Master/blob/fef3a358716dd5acc4318843a97a72bfde0f6797/src/master/resources/instance.py#L28

But the IW4Admin (IW4MAdmin-2024.8.16.1) client resolves the proper IPv4 
![image](https://github.com/user-attachments/assets/789282cb-d45c-4c85-a7b5-f6556315d2dd)

The `connect ip:port` command only seems to work with the ipv4. I assume the quake 3 protocol doesn't support ipv6?

Is there a way the ipv4 can be communicated to the master instead of the ipv6?

**Comment by RaidMax** [comment]
That master is outdated to what is currently running. The master only uses the IP of the request if your server is configured to use a LAN or loopback address in IW4MAdmin.

Think of it this way:
You have your server configured as 127.0.0.1, and make a request to the master over ipv6, there is no possible way for the master to know your external IPv4 address because you don’t provide it.

The solution is to use your external IPv4 address in the iw4madmin config when connecting to your servers, and that will send along to the master server.

**Comment by metalglove** [comment]
That makes sense yeah. However, I just tried it and it still reports IPv6 on the master server.

**Comment by metalglove** [comment]
After some time, it started reporting the correct server ip using the method you provided.

**Comment by metalglove** [comment]
I forgot to mention but the `webfront_url` possibly has a faulty format for `ADDRESS:PORT` on how URLs should work for IPv6. 
According to [RFC592#section6](https://datatracker.ietf.org/doc/html/rfc5952#section-6), the format is a valid representation, however it is NOT RECOMMENDED. 

It should be `[ADDRESS]:PORT` for usage in URLs.
And, thus likely also in the `connect` command.

I couldn't find it directly in the [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986), but Wikipedia references to it well

> Because IPv6 addresses contain colons, and URLs use colons to separate the host from the port number, an IPv6 address used as the host-part of a URL should be enclosed in square brackets,[[41]](https://en.wikipedia.org/wiki/IPv6#cite_note-rfc3986-41) e.g. http://[2001:db8:4006:812::200e] or http://[2001:db8:4006:812::200e]:8080/path/page.html.
[Quote](https://en.wikipedia.org/wiki/IPv6#cite_note-rfc3986-41:~:text=Because%20IPv6%20addresses%20contain%20colons%2C%20and%20URLs%20use%20colons%20to%20separate%20the%20host%20from%20the%20port%20number%2C%20an%20IPv6%20address%20used%20as%20the%20host%2Dpart%20of%20a%20URL%20should%20be%20enclosed%20in%20square%20brackets%2C%5B41%5D%20e.g.%20http%3A//%5B2001%3Adb8%3A4006%3A812%3A%3A200e%5D%20or%20http%3A//%5B2001%3Adb8%3A4006%3A812%3A%3A200e%5D%3A8080/path/page.html.)


As I have finally fixed my server to be IPv4 again, I can't test it.
But I thought it was noteworthy to at least mention to you guys.
